#!/bin/bash
yad --form \
    --title="Browser Installer" \
    --columns"=2" \
    --width="740" \
    --height="390" \
    --text="Browser Installer For Arch Based Systems" \
    --image="/usr/bin/Yad/PCTLC-LOGO-Small.png" \
--field="Install Firefox!/usr/bin/Yad/firefox.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/firefox-arch.sh'" \
--field="Remove Firefox!/usr/bin/Yad/firefox.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/remove-firefox-arch.sh'" \
--field="Install Google Chrome!/usr/bin/Yad/google-chrome.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/google-chrome-arch.sh'" \
--field="Remove Google Chrome!/usr/bin/Yad/google-chrome.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/remove-google-chrome-arch.sh'" \
--field="Install Brave!/usr/bin/Yad/brave.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/brave-arch.sh'" \
--field="Remove Brave!/usr/bin/Yad/brave.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/remove-brave-arch.sh'" \
--field="Install Vivaldi!/usr/bin/Yad/vivaldi.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/vivaldi-arch.sh'" \
--field="Remove Vivaldi!/usr/bin/Yad/vivaldi.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/remove-vivaldi-arch.sh'" \
--field="Install Opera!/usr/bin/Yad/opera.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/opera-arch.sh'" \
--field="Remove Opera!/usr/bin/Yad/opera.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/remove-opera-arch.sh'" \
--field="Install Edge!/usr/bin/Yad/web-browser.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/edge-browser-arch.sh'" \
--field="Remove Edge!/usr/bin/Yad/web-browser.svg!":fbtn "gnome-terminal -e '/usr/bin/Yad/Arch-Scripts/remove-edge-browser-arch.sh'" \
--button=Exit:1

